server:
  port: 8090

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: Shopping-Portal
  serviceProvider:
    url: Payment-Provider-Service/payment-provider/paynow/